version: '3.9'

services:
  server:
    build: ./server
    restart: unless-stopped
    depends_on:
      - pocketbase
      - redis
    ports:
      - '3000:3000'
  pocketbase:
    build: ./pocketbase
    ports:
      - '127.0.0.1:8090:8090'
    volumes:
      - pocketbase-data:/pb_data
  redis:
    image: redis
    ports:
      - '6379:6379'
  nginx:
    image: nginx
    depends_on:
      - server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email sasha.sirotyin09@gmail.com --agree-tos --no-eff-email --staging -d api.xoma-star.tk -d pb.xoma-star.tk
volumes:
  certbot-etc:
  certbot-var:
  pocketbase-data: